version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: "./backend/docker/Dockerfile"
    ports:
      - "5099:8080"
    networks:
      - base
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: "./frontend/docker/Dockerfile"
    ports:
      - "5098:8080"
    networks:
      - base

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

networks:
  base: