version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: "./backend/docker/Dockerfile"
    ports:
      - "5099:8080"
    networks:
      - base
#just for example
  frontend:
    build:
      context: .
      dockerfile: "./backend/docker/Dockerfile"
    ports:
      - "5098:8080"
    networks:
      - base

networks:
  base: